spring:
  application:
    name: snuxi

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: [email, profile]
            redirect-uri: "https://api.snuxi.com/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            client-name: Google

  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:}
        secret-key: ${AWS_SECRET_ACCESS_KEY:}
      s3:
        bucket: snuxi-dev-assets

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/snuxi?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USER:snuxi}
    password: ${DB_PASSWORD:snuxi_pw}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  forward-headers-strategy: native
  servlet:
    session:
      cookie:
        domain: snuxi.com
        same-site: none
        secure: true
        http-only: true