spring:
  application:
    name: snuxi
  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:}
        secret-key: ${AWS_SECRET_ACCESS_KEY:}
app:
  s3:
    bucket: snuxi-dev-assets